### ISSUE TITLE
[PD] Organise a study session about Time Management tools

### ISSUE THREAD

**Issue by bkarimii** [bkarimii/Coursework-Planner#26]
From Course-Fundamentals created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/Course-Fundamentals#12  

### Coursework content

Organise a study session with the pair you were assigned to during class - check out the Google Sheet.

Think about how you manage your time and which tools you use (add some examples and suggestions from our side). If you still need to start using them, research some and bring them to this meeting. 

### Estimated time in hours

2

### What is the purpose of this assignment?
- [x] Understand how you and your pair organise your time
- [x] Identify at least 2 time management tools each
- [x] With your pair, write a short paragraph about your findings
- [x] Share your findings in the "Time Management Tools" thread on your cohort Slack Channel. _Search for it on the channel. If the thread is not yet available, you can create it_
- [x] Read your peers text and react to it the the appropriate emoji

### How to submit
Add the link to your post on Slack on this coursework
Add a screenshot of your post on this coursework

**Comment by bkarimii** [comment]
https://docs.google.com/document/d/1QNISBzJ7wbes4_7cUKQ1BEtQFfkmBnrHu0IZ_xSpBQ0/edit?usp=sharing

**Comment by kfklein15** [comment]
AI checker is telling me that AI might have written 89% of your text. 

Using AI to write text is okay, but check for complicated words and phrases you wouldn't naturally use when speaking or writing. This way, your written English won't seem too different from how you talk.

Also, AI usually writes in American English. If you do not naturally use American English, make sure you review the spelling (in your text you left flavors instead of flavours).

**Comment by bkarimii** [comment]
Thank you @kfklein15 for your feedback, Yes i often use ChatGPT even as a Grammar Checker to correct my typos and grammatical eerors. And It sometimes change my own text as it attempt to make it fluent and natural . I will be more cautious in using AI. thank you for your time .

**Comment by kfklein15** [comment]
ChatGPT is NOT a good grammar checker. It's quite the opposite. It creates a lot of long and complex phrases instead of making communication simple and efficient. Download any grammar tool,hat will help you understand when you are using more words than needed, for example. I learned a lot from it.

**Comment by kfklein15** [comment]
@bkarimii please don't forget to close this issue - otherwise it stays open and we will see it on our "mentioned/assigned" list forever :D
