### ISSUE TITLE
[PD] Developers daily activities

### ISSUE THREAD

**Issue by bkarimii** [bkarimii/Coursework-Planner#27]
From Course-Fundamentals created by [kfklein15](https://github.com/kfklein15): CodeYourFuture/Course-Fundamentals#26  

### Coursework content

Research a developer's daily **activities** and **behaviours**. What will you expect to know or do when you get your first job?

Activities are specific actions, tasks, or operations to accomplish a particular goal or objective.
- For example: A marketing analyst must conduct market research and data analysis to identify consumer trends

Behaviour is the observable actions, reactions, or conduct of someone.
- For example: A marketing analyst must be able to effectively communicate complex data clearly and understandably to stakeholders. 

### Estimated time in hours

1

### What is the purpose of this assignment?

- [ ] Research a developer's daily activities and behaviours 
- [ ] Write at least 50 words on a Google Docs file
- [ ] Check the grammar using an available too, for example, Grammarly
- [ ] Share the file with your cohort - via thread or the share button directly
- [ ] Read two contents shared with you
- [ ] Leave at least 2 comments or questions on each text you read

### How to submit

Add the link to your Google Docs
Add a screenshot of your post sharing your coursework

**Comment by bkarimii** [comment]
[https://docs.google.com/document/d/1_1tUVW4FmH-W1PF9yeTiQTD999YIQsPWlfFhbyO056s/edit?usp=sharing](url)

**Comment by bkarimii** [comment]
![Image](https://github.com/bkarimii/Coursework-Planner/assets/125777824/a052a47f-f1ec-457f-ae7c-e2646736f1da)

**Comment by kfklein15** [comment]
I cannot open this link either. Can you paste it here again and tag me? Thanks!

**Comment by bkarimii** [comment]
https://docs.google.com/document/d/1_1tUVW4FmH-W1PF9yeTiQTD999YIQsPWlfFhbyO056s/edit?usp=drive_link

this is the link for the assignment  .sorry for the problem @kfklein15  and thank you for your time and review .

**Comment by kfklein15** [comment]
@bkarimii please don't forget to close this issue - otherwise it stays open and we will see it on our "mentioned/assigned" list forever :D
