### ISSUE TITLE
[PD] Write your personal statement

### ISSUE THREAD

**Issue by bkarimii** [bkarimii/Coursework-Planner#4]
From Course-Fundamentals created by [kfklein15](https://github.com/kfklein15): CodeYourFuture/Course-Fundamentals#23  

### Coursework content

Write 1 paragraph of your personal story/statement

### Estimated time in hours

1

### What is the purpose of this assignment?

1. Write a 1 paragraph statement - between 50 and 100 words. Think about skills you have that can be used in your future job in tech, and mention them in this text.
2. Check grammar using [Grammarly](https://www.grammarly.com/) or a similar tool. 
3. Add your statement to the "Personal Statement" thread on the Cohort Slack channel. If the thread hasn’t been created yet, please do it. 

### How to submit

Add the link to your post on Slack on this coursework
Add a screenshot of your post on this coursework

### Anything else?

[This video](https://slack.com/intl/en-gb/help/articles/202528808-Search-in-Slack) explains how to search in Slack

**Comment by bkarimii** [comment]
[https://docs.google.com/document/d/1W4p7sJopU1M3gPgxHX4hFQb-0Ecx4JjMWsQ53DS4tOg/edit?usp=sharing](url)

**Comment by bkarimii** [comment]
![Image](https://github.com/bkarimii/Coursework-Planner/assets/125777824/13e34cc9-b503-4314-ab3d-5ca47104655e)

**Comment by kfklein15** [comment]
@bkarimii , I cannot see the doc itself. Can you please add the link here again and tag me on it?

**Comment by bkarimii** [comment]
https://docs.google.com/document/d/1W4p7sJopU1M3gPgxHX4hFQb-0Ecx4JjMWsQ53DS4tOg/edit?usp=sharing

@kfklein15  I'm not sure why the shared link doesn't work now. I had given access to anyone with the link.

**Comment by kfklein15** [comment]
The text is good. You have great skills to become a software developer. 
AI checker: 52%

**Comment by bkarimii** [comment]
Thank you but this one was mine as it is personal 😅 and I just used ChatGPT for correct my typos and grammatical mistakes.  Probably that's why AI usage percentage is 52 . And this feedback was really helpful to be more aware of using AI .

**Comment by kfklein15** [comment]
@bkarimii please don't forget to close this issue - otherwise it stays open and we will see it on our "mentioned/assigned" list forever :D
