### ISSUE TITLE
[PD] Post something on Slack

### ISSUE THREAD

**Issue by bkarimii** [bkarimii/Coursework-Planner#5]
From Course-Fundamentals created by [kfklein15](https://github.com/kfklein15): CodeYourFuture/Course-Fundamentals#22  

### Coursework content

Check the Slack Rota spreadsheet and post something on your cohort Slack channel on your assigned day. Choose a subject you enjoy.

Remember to reply to every daily post with additional information, comments or opinion. 

### Estimated time in hours

0.5

### What is the purpose of this assignment?

1. Getting familiar with Slack
2. Using Slack on daily basis

### How to submit
1. Add the link to your post on Slack on this coursework
2. Add a screenshot of your post on this coursework

**Comment by bkarimii** [comment]
[https://cyf-introtodigital.slack.com/archives/C053HLLKPGE/p1688950159639159](url)

![Image](https://github.com/bkarimii/Coursework-Planner/assets/125777824/2d368b38-d96a-4c87-ab33-3c977354a910)

**Comment by kfklein15** [comment]
The link to Slack isn't working either - I'm not sure why. I cannot copy the text and check it. Could you copy and paste it here, and tag me? Thank you.

**Comment by bkarimii** [comment]
https://docs.google.com/document/d/1ouc94l_cYUOT0Xa3PWg3TqS7xFRrM_Hcteiq1L_Fs9k/edit?usp=sharing

Apparently, I should be more precise with the links that I share. This is the link to the posted text on Slack. Hopefully, this one works. @kfklein15

**Comment by kfklein15** [comment]
What an interesting topic!
AI checker: 52%
Grammarly picked up on quite some changes again, so make sure you use it more.

**Comment by bkarimii** [comment]
I will for next assignments.

**Comment by kfklein15** [comment]
@bkarimii please don't forget to close this issue - otherwise it stays open and we will see it on our "mentioned/assigned" list forever :D

**Comment by bkarimii** [comment]
Ah , ok l'll close it . Thank you
