### ISSUE TITLE
[PD] Professional skills research

### ISSUE THREAD

**Issue by bkarimii** [bkarimii/Coursework-Planner#6]
From Course-Fundamentals created by [kfklein15](https://github.com/kfklein15): CodeYourFuture/Course-Fundamentals#21  

### Coursework content

If you are here, it means you want a job in tech. But coding is not the only skill you must have to get a job. Professional skills are as important. 

But what is the primary goal of people that work in tech? We build Digital Products. And they are built with various roles, such as Sofware Developers, UX Designers, Testers, Product Owners/ Managers, and Scrum Masters. 

Research the professional skills needed for every role mentioned above and write three sentences describing these skills and why they are important.  

For example:  Software Engineers must be able to work collaboratively with all team members, so conflicts can be reduced.

### Estimated time in hours

1

### What is the purpose of this assignment?

1. Your research must be made available using Google Docs. We expect 3 phrases for every role, so at least 15 phrases in total. (20 min)
2. Review your grammar using any available tool, such as [Grammarly](https://www.grammarly.com/) (10 min)
3. Share your document on your cohort Slack channel (5 min)
4. Choose 2 people's research that has yet to be read. When you start reading it, add the 👀 emoji to their thread so everyone knows you are reading it. (2 min)
5. Read their content and add at least 1 comment on each Google doc. (20 min)
6. When you have read someone’s research, react with an appropriate emoji to their post on Slack so they know you’ve done it. (2 min)

### How to submit

1. Add the link to your post on Slack on this coursework
2. Add a screenshot of your post on this coursework
3. Add the link of your Google Doc on this coursework

### Anything else?

- How to create a Google Docs: suggested [video](https://www.youtube.com/watch?v=I0OqnItA-zA).
- How to comment on Google Docs: suggested [video](https://edu.gcfglobal.org/en/googledocuments/adding-and-replying-to-comments/1/) 
- You can use job descriptions to identify the non-technical skills employers seek. Some good resources are  [CW Jobs](https://www.cwjobs.co.uk/), [Linkedin](https://www.linkedin.com/),[ Indeed](https://uk.indeed.com/), or any job board.

**Comment by bkarimii** [comment]
[https://docs.google.com/document/d/1I3PqNaZ9BVea_uoIiBbY_AmsWKiWyojCXC1yfwuJLho/edit?usp=sharing]()

**Comment by bkarimii** [comment]
![Image](https://github.com/bkarimii/Coursework-Planner/assets/125777824/22236ec3-8599-48da-b7f5-289e0432b4be)

**Comment by kfklein15** [comment]
@bkarimii , I cannot open the link to the doc for some reason. Can you add it here again and tag me, please?

**Comment by bkarimii** [comment]
https://docs.google.com/document/d/1az7cvU-AFjjZlMNZmGEB7ibnegZNjmH_PHhGflTKPOM/edit?usp=sharing

This link should work. Thank you for your patience with all my broken links, lol. Your help your time, and your feedback are much appreciated.

**Comment by kfklein15** [comment]
Thanks for sending this to me.
- AI checker says 50%, possibly written by AI. Try to write your text as much as possible to practice it. As a developer, you will have to communicate in writing a lot, so knowing how to write things yourself will make a difference. Plus, if what is written doesn't "sound" like you, this will stand-out. 
- You should not leave a space before the punctuation. Some examples from your text: 
      - 2 : problem = 2: problem
      - should have , breaking = should have, breaking
- Example of hyphen missing: problem-solving
